name: demo-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch:
    inputs:
      name:
        description: "cluster-name"
        type: string
        required: true
        default: "GKE-cluster"

permissions: {}

jobs:
  job1:
    name: job1
    runs-on: ubuntu-latest
    steps:
      - name: Print cluster name
        run: echo "${{ github.event.inputs.name || 'GKE-cluster' }}"

  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - name: Print cluster name
        run: echo "${{ github.event.inputs.name || 'GKE-cluster' }}"
