name: demo-workflow

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  workflow_dispatch: 
    inputs: 
      name:
        description: "cluster-name"
        type: String
        required: true
        default: "GKE-cluster"
      

permissions: {}

jobs:
  job1:
    name: "job1"
    runs-on: ubuntu-latest
    steps:
      - run: echo "job1"

  job2:
    name: job2
    runs-on: windows-latest
    steps:
      - run: echo "job2"
